### ISSUE TITLE
A possible mistake in the paper

### ISSUE THREAD

**Issue by eastontwo** [RisingEntropy/LPFInISR#2]
I think I have discovered a small mistake in the paper. On page 4, paragraph 4.1, there is a mathematical formula:
$$Conv_{i,j}=\sum_{p,q}I_{i-p,j-1}K_{p,q}$$
I wonder if it should be
$$Conv_{i,j}=\sum_{p,q}I_{i-p,j-q}K_{p,q}$$
I'm not sure if I was wrong and i would greatly appreciate it if you could answer.

**Comment by RisingEntropy** [comment]
Oh, you are right. We are so sorry for this careless mistake! Thanks for pointing out! I will fix it on arxiv.
